import FoodView from "@/components/food-view/FoodView";
import { Metadata } from "next";
import { memo } from "react";

export const metadata: Metadata = {
  title: "About page",
  description: "Generated by create next app",
};

// useRouter = useNavigate

const About = async () => {
  const response = await fetch("https://dummyjson.com/recipes");
  const data = await response.json();

  return (
    <div className="Page">
      <h2>About SSR</h2>
      <FoodView data={data?.recipes}/>
    </div>
  );
};

export default memo(About);
